# ============================================================
# Azure App Registration Setup — Full Automation
# ============================================================
# This script:
#   1. Logs you into Azure (opens browser)
#   2. Creates an app registration
#   3. Adds all required permissions
#   4. Grants admin consent
#   5. Assigns Exchange Administrator role
#   6. Outputs Tenant ID, Client ID, Client Secret
#   7. Updates Google Sheet with credentials
# ============================================================

param(
    [string]$AppName = "TenantSetupAutomation",
    [string]$SheetId = "1fuwvD1G0zlTpLc5pF0bPOnEMnIBa65StVcXww3cJQ-M"
)

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Azure App Registration Setup — Full Automation" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# ─── Step 1: Check Azure CLI ─────────────────────────────────
Write-Host "[1/9] Checking Azure CLI..." -ForegroundColor Yellow
$azVersion = az version 2>$null
if (-not $azVersion) {
    Write-Host "[ERROR] Azure CLI not installed!" -ForegroundColor Red
    Write-Host "Install from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows" -ForegroundColor Red
    Write-Host "Or run: winget install Microsoft.AzureCLI" -ForegroundColor Yellow
    exit 1
}
Write-Host "[OK] Azure CLI installed" -ForegroundColor Green

# ─── Step 2: Login to Azure (with tenant-only access) ────────
Write-Host ""
Write-Host "[2/9] Logging into Azure (browser will open)..." -ForegroundColor Yellow
Write-Host "     Select your admin account in the browser" -ForegroundColor Gray

# Use --allow-no-subscriptions for tenants without Azure subscription
az login --allow-no-subscriptions --output none
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Login failed" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Logged in successfully" -ForegroundColor Green

# ─── Step 3: Get Tenant ID and Admin Email ───────────────────
Write-Host ""
Write-Host "[3/9] Getting Tenant ID and Admin Email..." -ForegroundColor Yellow
$tenantId = az account show --query tenantId -o tsv
$adminEmail = az account show --query user.name -o tsv
if (-not $tenantId) {
    Write-Host "[ERROR] Could not get Tenant ID" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Tenant ID: $tenantId" -ForegroundColor Green
Write-Host "[OK] Admin Email: $adminEmail" -ForegroundColor Green

# ─── Step 4: Create App Registration ─────────────────────────
Write-Host ""
Write-Host "[4/9] Creating App Registration '$AppName'..." -ForegroundColor Yellow

# Check if app already exists
$existingApp = az ad app list --display-name $AppName --query "[0].appId" -o tsv 2>$null
if ($existingApp) {
    Write-Host "[INFO] App '$AppName' already exists, using it" -ForegroundColor Yellow
    $clientId = $existingApp
} else {
    # Create new app
    $appJson = az ad app create --display-name $AppName --sign-in-audience AzureADMyOrg --output json
    $app = $appJson | ConvertFrom-Json
    $clientId = $app.appId
}
Write-Host "[OK] Client ID: $clientId" -ForegroundColor Green

# ─── Step 5: Create Client Secret ────────────────────────────
Write-Host ""
Write-Host "[5/9] Creating Client Secret..." -ForegroundColor Yellow
$secretJson = az ad app credential reset --id $clientId --append --display-name "AutoGenerated" --years 2 --output json 2>$null
if (-not $secretJson) {
    # Try alternative method
    $secretJson = az ad app credential reset --id $clientId --years 2 --output json
}
$secret = $secretJson | ConvertFrom-Json
$clientSecret = $secret.password
Write-Host "[OK] Client Secret created" -ForegroundColor Green

# ─── Step 6: Create Service Principal ────────────────────────
Write-Host ""
Write-Host "[6/9] Creating Service Principal..." -ForegroundColor Yellow
$spExists = az ad sp show --id $clientId 2>$null
if (-not $spExists) {
    az ad sp create --id $clientId --output none
}
$spId = az ad sp show --id $clientId --query id -o tsv
Write-Host "[OK] Service Principal created" -ForegroundColor Green

# ─── Step 7: Add API Permissions ─────────────────────────────
Write-Host ""
Write-Host "[7/9] Adding API Permissions..." -ForegroundColor Yellow

# Microsoft Graph API ID
$graphApiId = "00000003-0000-0000-c000-000000000000"

# Graph Permission IDs (Application permissions)
$graphPermissions = @{
    "Directory.ReadWrite.All" = "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
    "User.ReadWrite.All" = "741f803b-c850-494e-b5df-cde7c675a1ca"
    "Domain.ReadWrite.All" = "7e05723c-0bb0-42da-be95-ae9f08a6e53c"
    "Policy.ReadWrite.ConditionalAccess" = "01c0a623-fc9b-48e9-b794-0756f8e8f067"
    "Policy.ReadWrite.AuthenticationMethod" = "29c18626-4985-4dcd-85c0-193eef327366"
    "Mail.ReadWrite" = "e2a3a72e-5f79-4c64-b1b1-878b674786c9"
    "Organization.ReadWrite.All" = "292d869f-3427-49a8-9dab-8c70152b74e9"
}

# Office 365 Exchange Online API ID
$exchangeApiId = "00000002-0000-0ff1-ce00-000000000000"

# Exchange Permission ID (full_access_as_app)
$exchangeFullAccess = "dc890d15-9560-4a4c-9b7f-a736ec74ec40"

# Build required resource access array
$requiredResourceAccess = @()

# Add Graph permissions
$graphAccess = @{
    resourceAppId = $graphApiId
    resourceAccess = @()
}
foreach ($perm in $graphPermissions.GetEnumerator()) {
    $graphAccess.resourceAccess += @{
        id = $perm.Value
        type = "Role"
    }
    Write-Host "     Adding: $($perm.Key)" -ForegroundColor Gray
}
$requiredResourceAccess += $graphAccess

# Add Exchange permission
$exchangeAccess = @{
    resourceAppId = $exchangeApiId
    resourceAccess = @(@{
        id = $exchangeFullAccess
        type = "Role"
    })
}
$requiredResourceAccess += $exchangeAccess
Write-Host "     Adding: full_access_as_app (Exchange)" -ForegroundColor Gray

# Convert to JSON and update app
$bodyJson = @{
    requiredResourceAccess = $requiredResourceAccess
} | ConvertTo-Json -Depth 10 -Compress

# Update app with permissions
az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications(appId='$clientId')" --headers "Content-Type=application/json" --body $bodyJson 2>$null

Write-Host "[OK] Permissions added" -ForegroundColor Green

# ─── Step 8: Grant Admin Consent ─────────────────────────────
Write-Host ""
Write-Host "[8/9] Granting Admin Consent..." -ForegroundColor Yellow
Write-Host "     This may take a moment..." -ForegroundColor Gray

# Wait for permissions to propagate
Start-Sleep -Seconds 5

# Grant admin consent
az ad app permission admin-consent --id $clientId 2>$null

Write-Host "[OK] Admin consent granted" -ForegroundColor Green

# ─── Assign Exchange Administrator Role ──────────────────────
Write-Host ""
Write-Host "[BONUS] Assigning Exchange Administrator Role..." -ForegroundColor Yellow

# Get Exchange Administrator role ID
$exchangeAdminRole = az rest --method GET --uri "https://graph.microsoft.com/v1.0/directoryRoles" --query "value[?displayName=='Exchange Administrator'].id" -o tsv 2>$null

if (-not $exchangeAdminRole) {
    # Activate the role first
    $roleTemplateId = "29232cdf-9323-42fd-ade2-1d097af3e4de" # Exchange Administrator template ID
    az rest --method POST --uri "https://graph.microsoft.com/v1.0/directoryRoles" --headers "Content-Type=application/json" --body "{`"roleTemplateId`":`"$roleTemplateId`"}" 2>$null
    Start-Sleep -Seconds 2
    $exchangeAdminRole = az rest --method GET --uri "https://graph.microsoft.com/v1.0/directoryRoles" --query "value[?displayName=='Exchange Administrator'].id" -o tsv 2>$null
}

if ($exchangeAdminRole -and $spId) {
    # Assign role to service principal
    $body = "{`"@odata.id`":`"https://graph.microsoft.com/v1.0/directoryObjects/$spId`"}"
    az rest --method POST --uri "https://graph.microsoft.com/v1.0/directoryRoles/$exchangeAdminRole/members/`$ref" --headers "Content-Type=application/json" --body $body 2>$null
    Write-Host "[OK] Exchange Administrator role assigned" -ForegroundColor Green
} else {
    Write-Host "[WARN] Could not assign Exchange Administrator role automatically" -ForegroundColor Yellow
    Write-Host "       Manual: Azure Portal > Roles and administrators > Exchange Administrator > Add your app" -ForegroundColor Gray
}

# ─── Step 9: Update Google Sheet ─────────────────────────────
Write-Host ""
Write-Host "[9/9] Updating Google Sheet..." -ForegroundColor Yellow
Write-Host "     Admin Email: $adminEmail" -ForegroundColor Gray
Write-Host "     Looking for row with this email..." -ForegroundColor Gray

# Save credentials to a JSON file for the Python script to use
$credsJson = @{
    tenant_id = $tenantId
    client_id = $clientId
    client_secret = $clientSecret
    admin_email = $adminEmail
    sheet_id = $SheetId
} | ConvertTo-Json

$credsFile = Join-Path $PSScriptRoot "temp_creds.json"
$credsJson | Out-File -FilePath $credsFile -Encoding UTF8 -Force

# Run Python script to update Google Sheet
$pythonScript = @"
import json
import os

# Check if gspread is available
try:
    import gspread
    from google.oauth2.service_account import Credentials
except ImportError:
    print("[WARN] gspread not installed. Run: pip install gspread google-auth")
    print("[INFO] Skipping Google Sheet update")
    exit(0)

# Load credentials
creds_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "temp_creds.json")
with open(creds_file) as f:
    creds = json.load(f)

tenant_id = creds['tenant_id']
client_id = creds['client_id']
client_secret = creds['client_secret']
admin_email = creds['admin_email']
sheet_id = creds['sheet_id']

print(f"[INFO] Looking for: {admin_email}")

# Try to find Google service account credentials
sa_file = None
for f in ['service_account.json', 'google_creds.json', 'credentials.json']:
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), f)
    if os.path.exists(path):
        sa_file = path
        break

if not sa_file:
    print("[WARN] No Google service account file found")
    print("[INFO] Create service_account.json with Google Cloud credentials")
    print("[INFO] Skipping Google Sheet update")
    exit(0)

# Connect to Google Sheets
scopes = ['https://www.googleapis.com/auth/spreadsheets']
credentials = Credentials.from_service_account_file(sa_file, scopes=scopes)
gc = gspread.authorize(credentials)

# Open sheet
sheet = gc.open_by_key(sheet_id)

# Find Settings tab or first sheet
try:
    ws = sheet.worksheet('Settings')
except:
    ws = sheet.sheet1

# Get all values
all_values = ws.get_all_values()

# Find row with admin email (check column A, B, C, D)
row_found = None
for i, row in enumerate(all_values):
    for cell in row[:10]:  # Check first 10 columns
        if admin_email.lower() in cell.lower():
            row_found = i + 1  # 1-indexed
            break
    if row_found:
        break

if row_found:
    # Update columns E, F, G (5, 6, 7)
    ws.update_cell(row_found, 5, tenant_id)   # Column E
    ws.update_cell(row_found, 6, client_id)   # Column F
    ws.update_cell(row_found, 7, client_secret)  # Column G
    print(f"[OK] Updated row {row_found} with credentials")
else:
    print(f"[WARN] Admin email '{admin_email}' not found in sheet")
    print("[INFO] Please manually add credentials to the sheet")

# Cleanup
os.remove(creds_file)
"@

$pythonFile = Join-Path $PSScriptRoot "update_sheet_temp.py"
$pythonScript | Out-File -FilePath $pythonFile -Encoding UTF8 -Force

# Try to run Python script
try {
    python $pythonFile 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "[OK] Google Sheet updated" -ForegroundColor Green
    }
} catch {
    Write-Host "[INFO] Could not update Google Sheet automatically" -ForegroundColor Yellow
    Write-Host "       Please copy credentials manually" -ForegroundColor Gray
}

# Cleanup temp files
Remove-Item $pythonFile -ErrorAction SilentlyContinue
Remove-Item $credsFile -ErrorAction SilentlyContinue

# ─── Output Results ──────────────────────────────────────────
Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "  SETUP COMPLETE!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Your credentials:" -ForegroundColor Cyan
Write-Host ""
Write-Host "TENANT_ID=$tenantId" -ForegroundColor White
Write-Host "CLIENT_ID=$clientId" -ForegroundColor White
Write-Host "CLIENT_SECRET=$clientSecret" -ForegroundColor White
Write-Host "ADMIN_EMAIL=$adminEmail" -ForegroundColor White
Write-Host ""

# Save to .env file
$envContent = @"
TENANT_ID=$tenantId
CLIENT_ID=$clientId
CLIENT_SECRET=$clientSecret
ADMIN_EMAIL=$adminEmail
"@

$envPath = Join-Path $PSScriptRoot ".env"
$envContent | Out-File -FilePath $envPath -Encoding UTF8 -Force
Write-Host "[OK] Saved to: $envPath" -ForegroundColor Green

# Also output for copy-paste
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Copy these values to your Google Sheet:" -ForegroundColor Cyan
Write-Host "  (Columns E, F, G in the row with admin email)" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Admin Email:   $adminEmail" -ForegroundColor Yellow
Write-Host "Tenant ID:     $tenantId" -ForegroundColor Yellow
Write-Host "Client ID:     $clientId" -ForegroundColor Yellow
Write-Host "Client Secret: $clientSecret" -ForegroundColor Yellow
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Wait 5 minutes for permissions to propagate, then run:" -ForegroundColor Gray
Write-Host "  python tenant_setup_automation.py" -ForegroundColor White
Write-Host ""
